import { Link } from 'react-router-dom'
import { ArrowUpRight, Database, Server, ShieldCheck, Users } from 'lucide-react'
import { useAuth } from '@/features/auth'

export const AdminPage = () => {
  const { user } = useAuth()
  const sections = [
    { title: 'User management', description: 'Create, activate and remove operator identities.', to: '/users', icon: Users, tone: 'bg-violet-50 text-[var(--violet)]' },
    { title: 'Device inventory', description: 'Review monitored endpoints and their status.', to: '/devices', icon: Server, tone: 'bg-teal-50 text-[var(--cyan)]' },
    { title: 'Security logs', description: 'Search events generated by security systems.', to: '/logs', icon: Database, tone: 'bg-amber-50 text-[var(--amber)]' },
  ]

  return <div className="page-frame space-y-6">
    <div className="page-hero rounded-2xl p-6 text-white md:p-8"><div className="relative z-10"><p className="eyebrow text-[var(--cyan)]">Control center</p><h1 className="mt-2 text-3xl font-bold tracking-tight md:text-4xl">Administration</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/65">Keep the workspace clean, access-aware and ready for the next investigation.</p></div></div>
    <div className="surface flex flex-wrap items-center gap-4 rounded-2xl p-5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-50 text-[var(--cyan)]"><ShieldCheck size={20} /></span><div><p className="text-xs uppercase tracking-wider text-[var(--muted)]">Signed in as</p><p className="mt-1 font-semibold text-[var(--ink)]">{user?.username}</p><p className="text-sm text-[var(--muted)]">{user?.email} - {user?.roles?.[0] || 'operator'}</p></div></div>
    <div className="grid grid-cols-1 gap-5 md:grid-cols-3">{sections.map(({ title, description, to, icon: Icon, tone }) => <Link key={to} to={to} className="surface group rounded-2xl p-6 transition hover:-translate-y-1 hover:border-[var(--cyan)]"><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${tone}`}><Icon size={20} /></span><h2 className="mt-5 font-semibold text-[var(--ink)]">{title}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-[var(--muted)]">{description}</p><span className="mt-5 flex items-center gap-2 text-sm font-semibold text-[var(--cyan)]">Open section <ArrowUpRight size={15} className="transition group-hover:translate-x-1 group-hover:-translate-y-1" /></span></Link>)}</div>
  </div>
}
