import { Link } from 'react-router-dom'
import { useAuth } from '@/features/auth'

export const AdminPage = () => {
  const { user } = useAuth()
  const sections = [
    { title: 'User management', description: 'Create, activate and remove users.', to: '/users' },
    { title: 'Device inventory', description: 'Review monitored devices and their status.', to: '/devices' },
    { title: 'Security logs', description: 'Search events generated by security systems.', to: '/logs' },
  ]

  return <div>
    <h1 className="mb-6 text-3xl font-bold text-gray-900">Administration</h1>
    <div className="mb-6 rounded-lg bg-white p-6 shadow"><p className="text-sm text-gray-500">Signed in as</p><p className="mt-1 text-lg font-semibold text-gray-900">{user?.username}</p><p className="text-gray-600">{user?.email}</p></div>
    <div className="grid grid-cols-1 gap-6 md:grid-cols-3">{sections.map((section) => <Link key={section.to} to={section.to} className="rounded-lg bg-white p-6 shadow hover:bg-gray-50"><h2 className="font-semibold text-gray-900">{section.title}</h2><p className="mt-2 text-sm text-gray-600">{section.description}</p><span className="mt-4 block text-sm font-medium text-brand-600">Open section</span></Link>)}</div>
  </div>
}
