import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, Pencil, Save, Sparkles, Trash2 } from 'lucide-react'
import { aiAPI, alertsAPI } from '@/services/api'
import { useAuth } from '@/features/auth/hooks/useAuth'

interface AlertDetails { id: string; title: string; description?: string; severity: string; status: string; source?: string; detection_time?: string; created_at?: string; updated_at?: string }

interface WorkflowToolCall { tool: string; status: string; error_message?: string | null; summary?: string | null }
interface WorkflowResult { workflow: string; answer: string; provider: string; tool_calls: WorkflowToolCall[]; generated_at?: string }

export const AlertDetailPage = () => {
  const { user } = useAuth()
  const canManageAlerts = user?.permissions?.includes('manage_alerts') ?? false
  const canUseAI = user?.permissions?.includes('use_ai_agent') ?? false
  const { alertId } = useParams<{ alertId: string }>(); const navigate = useNavigate()
  const [alert, setAlert] = useState<AlertDetails | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false)
  const [triage, setTriage] = useState<WorkflowResult | null>(null); const [triaging, setTriaging] = useState(false); const [triageError, setTriageError] = useState('')
  useEffect(() => { if (!alertId) return; alertsAPI.getAlert(alertId).then((response) => setAlert(response as AlertDetails)).catch((requestError: Error) => setError(requestError.message)).finally(() => setLoading(false)) }, [alertId])
  const updateAlert = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!alert || !alertId) return; setSaving(true); setError(''); const form = new FormData(event.currentTarget); try { const response = await alertsAPI.updateAlert(alertId, { title: form.get('title'), description: form.get('description'), severity: form.get('severity'), status: form.get('status'), source: form.get('source') }); setAlert({ ...alert, ...(response as Partial<AlertDetails>) }); setEditing(false) } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to update alert') } finally { setSaving(false) } }
  const deleteAlert = async () => { if (!alertId || !window.confirm('Delete this alert?')) return; try { await alertsAPI.deleteAlert(alertId); navigate('/alerts') } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Unable to delete alert') } }
  const runTriage = async () => { if (!alertId) return; setTriaging(true); setTriageError(''); try { setTriage(await aiAPI.runAlertTriage(alertId) as WorkflowResult) } catch (requestError) { setTriageError(requestError instanceof Error ? requestError.message : 'Unable to run triage') } finally { setTriaging(false) } }
  if (loading) return <div className="detail-shell text-[var(--muted)]">Loading alert...</div>
  if (error || !alert) return <div className="detail-shell rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">Unable to load alert: {error || 'Alert not found'}</div>
  return <div className="detail-shell space-y-6">
    <Link to="/alerts" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--cyan)] hover:text-[var(--ink)]"><ArrowLeft size={15} /> Back to alerts</Link>
    <div className="page-hero rounded-2xl p-6 text-white md:p-8"><div className="relative z-10 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-[var(--cyan)]">Security signal</p><h1 className="mt-2 max-w-2xl text-3xl font-bold tracking-tight md:text-4xl">{alert.title}</h1><p className="mt-2 text-sm text-white/65">{alert.source || 'Unknown source'}</p></div><span className={`status-chip status-chip--${alert.severity.toLowerCase()}`}>{alert.severity}</span></div></div>
    <div className="detail-panel p-6"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-red-50 text-[var(--coral)]"><AlertTriangle size={20} /></span><div><p className="text-xs uppercase tracking-wider text-[var(--muted)]">Current status</p><span className={`status-chip status-chip--${alert.status.toLowerCase()}`}>{alert.status}</span></div></div>{canManageAlerts && <div className="flex gap-2"><button onClick={() => setEditing(!editing)} className="btn-primary"><Pencil size={15} />{editing ? 'Cancel' : 'Edit'}</button><button onClick={deleteAlert} className="btn-danger"><Trash2 size={15} />Delete</button></div>}</div>
      {canManageAlerts && editing && <form onSubmit={updateAlert} className="mb-6 space-y-4 border-b border-[var(--line)] pb-6"><input name="title" required defaultValue={alert.title} className="field-control" /><textarea name="description" defaultValue={alert.description} className="field-control" rows={3} /><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><select name="severity" defaultValue={alert.severity} className="field-control"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><select name="status" defaultValue={alert.status} className="field-control"><option>NEW</option><option>ACKNOWLEDGED</option><option>INVESTIGATING</option><option>RESOLVED</option><option>FALSE_POSITIVE</option></select><input name="source" defaultValue={alert.source} placeholder="Source" className="field-control" /></div><button disabled={saving} type="submit" className="btn-primary disabled:opacity-50"><Save size={15} />{saving ? 'Saving...' : 'Save changes'}</button></form>}
      <div><h2 className="text-xl font-bold text-[var(--ink)]">Signal context</h2><p className="mt-2 max-w-3xl leading-7 text-[var(--ink-soft)]">{alert.description || 'No description has been added to this alert.'}</p></div><dl className="mt-6 grid grid-cols-1 gap-5 border-t border-[var(--line)] pt-6 sm:grid-cols-2"><div><dt className="text-xs uppercase tracking-wider text-[var(--muted)]">Source</dt><dd className="mt-1 text-[var(--ink-soft)]">{alert.source || 'Unknown'}</dd></div><div><dt className="text-xs uppercase tracking-wider text-[var(--muted)]">Detected</dt><dd className="mt-1 text-sm text-[var(--ink-soft)]">{alert.detection_time || 'Unknown'}</dd></div><div><dt className="text-xs uppercase tracking-wider text-[var(--muted)]">Created</dt><dd className="mt-1 text-sm text-[var(--ink-soft)]">{alert.created_at || 'Unknown'}</dd></div><div><dt className="text-xs uppercase tracking-wider text-[var(--muted)]">Updated</dt><dd className="mt-1 text-sm text-[var(--ink-soft)]">{alert.updated_at || 'Unknown'}</dd></div></dl>
      {canUseAI && <section className="mt-6 border-t border-[var(--line)] pt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Assisted analysis</p><h2 className="mt-1 text-xl font-bold text-[var(--ink)]">AI triage</h2><p className="mt-1 text-sm text-[var(--muted)]">Correlate this alert with its device, IP intelligence, logs and linked investigation.</p></div><button onClick={runTriage} disabled={triaging} className="btn-primary disabled:opacity-50"><Sparkles size={15} />{triaging ? 'Analyzing...' : 'Triage with AI'}</button></div>
        {triageError && <p className="mt-3 text-sm text-red-700">Unable to run triage: {triageError}</p>}
        {triage && <div className="mt-4 rounded-xl border border-[var(--line)] bg-slate-50/70 p-4"><div className="flex flex-wrap items-center gap-2"><span className="status-chip status-chip--low">{triage.provider}</span>{triage.tool_calls.filter((call) => call.status === 'SUCCESS').map((call) => <span key={call.tool} className="status-chip status-chip--low">{call.tool}</span>)}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[var(--ink-soft)]">{triage.answer}</p>{triage.generated_at && <p className="mt-2 font-mono text-[10px] text-[var(--muted)]">{triage.generated_at}</p>}</div>}
      </section>}
    </div>
  </div>
}
